apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: halo-factory-floor
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.factoryFloor.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: halo-factory-floor
                port:
                  number: 8888